import type {
  CommunityNeed,
  DemoUser,
  DonationLocation,
  Resource,
  VolunteerOpportunity,
} from "@/types";

/** Seeded San Francisco Bay Area demo data — fictional for demonstration only. */
export const DEMO_CENTER = { lat: 37.7749, lng: -122.4194, label: "San Francisco, CA" };

export const IMPACT_STATS = {
  essentialsMatched: 12840,
  donationsCoordinated: 3126,
  activeLocations: 186,
  communityVolunteers: 942,
};

export const demoUsers: DemoUser[] = [
  {
    email: "donor@demo.openhands",
    password: "demo1234",
    name: "Alex Donor",
    role: "donor",
  },
  {
    email: "host@demo.openhands",
    password: "demo1234",
    name: "Jordan Host",
    role: "host",
    organization: "Harbor Bridge Collective",
  },
  {
    email: "provider@demo.openhands",
    password: "demo1234",
    name: "Sam Provider",
    role: "provider",
    organization: "Bayview Community Pantry",
  },
  {
    email: "admin@demo.openhands",
    password: "demo1234",
    name: "Riley Admin",
    role: "admin",
    organization: "OpenHands Moderators",
  },
];

export const resources: Resource[] = [
  {
    id: "res-1",
    name: "Bayview Community Pantry",
    slug: "bayview-community-pantry",
    description: "Walk-in grocery bags and hot meals. No appointment needed for dinner service.",
    category: "food",
    address: "2145 3rd St",
    city: "San Francisco",
    state: "CA",
    postalCode: "94107",
    latitude: 37.7612,
    longitude: -122.3889,
    phone: "(415) 555-0142",
    website: "https://example.org/bayview-pantry",
    verificationStatus: "verified_org",
    lastVerifiedAt: "2026-07-08",
    openStatus: "open_now",
    nextOpenLabel: "Open until 7:00 PM",
    walkInAllowed: true,
    appointmentRequired: false,
    idRequired: false,
    familyFriendly: true,
    petFriendly: false,
    wheelchairAccessible: true,
    languages: ["English", "Spanish"],
    essentials: ["Hot meals", "Grocery bags", "Fresh produce"],
    eligibility: "Open to anyone. Families welcome.",
    accessibility: "Ramp entrance, accessible restroom.",
    hours: "Mon–Sat 11:00 AM – 7:00 PM",
    orgName: "Bayview Community Pantry",
  },
  {
    id: "res-2",
    name: "Mission Evening Meal",
    slug: "mission-evening-meal",
    description: "Hot dinner served nightly. Volunteers pack leftovers for the next morning.",
    category: "food",
    address: "298 Valencia St",
    city: "San Francisco",
    state: "CA",
    postalCode: "94103",
    latitude: 37.7685,
    longitude: -122.4221,
    phone: "(415) 555-0188",
    verificationStatus: "verified_moderator",
    lastVerifiedAt: "2026-07-09",
    openStatus: "opens_later",
    nextOpenLabel: "Opens today at 5:00 PM",
    walkInAllowed: true,
    appointmentRequired: false,
    idRequired: false,
    familyFriendly: true,
    petFriendly: true,
    wheelchairAccessible: true,
    languages: ["English", "Spanish", "Chinese"],
    essentials: ["Dinner", "Water", "To-go containers"],
    eligibility: "All ages. Pets allowed outdoors.",
    accessibility: "Step-free entry.",
    hours: "Daily 5:00 PM – 8:00 PM",
    orgName: "Mission Evening Meal",
  },
  {
    id: "res-3",
    name: "Sunrise Day Center Meals",
    slug: "sunrise-day-center-meals",
    description: "Breakfast and lunch with seating, charging outlets, and restrooms.",
    category: "food",
    address: "1001 Market St",
    city: "San Francisco",
    state: "CA",
    postalCode: "94103",
    latitude: 37.7812,
    longitude: -122.4114,
    phone: "(415) 555-0110",
    verificationStatus: "verified_org",
    lastVerifiedAt: "2026-07-07",
    openStatus: "open_now",
    nextOpenLabel: "Open until 2:00 PM",
    walkInAllowed: true,
    appointmentRequired: false,
    idRequired: false,
    familyFriendly: true,
    petFriendly: false,
    wheelchairAccessible: true,
    languages: ["English"],
    essentials: ["Breakfast", "Lunch", "Device charging"],
    eligibility: "Walk-in welcome.",
    accessibility: "Elevator available.",
    hours: "Mon–Fri 8:00 AM – 2:00 PM",
    orgName: "Sunrise Day Center",
  },
  {
    id: "res-4",
    name: "Harbor Overnight Shelter",
    slug: "harbor-overnight-shelter",
    description: "Emergency overnight beds with intake starting early evening. Availability changes nightly.",
    category: "shelter",
    address: "450 Townsend St",
    city: "San Francisco",
    state: "CA",
    postalCode: "94107",
    latitude: 37.7728,
    longitude: -122.3975,
    phone: "(415) 555-0199",
    verificationStatus: "verified_org",
    lastVerifiedAt: "2026-07-10",
    openStatus: "opens_later",
    nextOpenLabel: "Intake opens at 6:00 PM",
    walkInAllowed: true,
    appointmentRequired: false,
    idRequired: false,
    familyFriendly: false,
    petFriendly: false,
    wheelchairAccessible: true,
    languages: ["English", "Spanish"],
    essentials: ["Overnight bed", "Blankets", "Restrooms"],
    eligibility: "Adults 18+. Check in for same-night availability.",
    accessibility: "Accessible showers and beds available.",
    hours: "Intake 6:00 PM – 9:00 PM",
    orgName: "Harbor Overnight Shelter",
  },
  {
    id: "res-5",
    name: "Family Safe Stay",
    slug: "family-safe-stay",
    description: "Family-friendly temporary shelter with separate family rooms when available.",
    category: "shelter",
    address: "88 Cesar Chavez St",
    city: "San Francisco",
    state: "CA",
    postalCode: "94103",
    latitude: 37.7499,
    longitude: -122.4032,
    phone: "(415) 555-0166",
    verificationStatus: "verified_moderator",
    lastVerifiedAt: "2026-07-06",
    openStatus: "appointment",
    nextOpenLabel: "Call for intake",
    walkInAllowed: false,
    appointmentRequired: true,
    idRequired: false,
    familyFriendly: true,
    petFriendly: false,
    wheelchairAccessible: true,
    languages: ["English", "Spanish"],
    essentials: ["Family rooms", "Meals", "Case support"],
    eligibility: "Families with children. Intake by phone.",
    accessibility: "Accessible rooms on request.",
    hours: "Intake line 9:00 AM – 5:00 PM",
    orgName: "Family Safe Stay Network",
  },
  {
    id: "res-6",
    name: "Youth Bridge Shelter",
    slug: "youth-bridge-shelter",
    description: "Short-term shelter and counseling for youth ages 18–24.",
    category: "shelter",
    address: "1230 Polk St",
    city: "San Francisco",
    state: "CA",
    postalCode: "94109",
    latitude: 37.7881,
    longitude: -122.4203,
    phone: "(415) 555-0133",
    verificationStatus: "verified_org",
    lastVerifiedAt: "2026-07-05",
    openStatus: "open_now",
    nextOpenLabel: "Open for daytime services",
    walkInAllowed: true,
    appointmentRequired: false,
    idRequired: false,
    familyFriendly: false,
    petFriendly: false,
    wheelchairAccessible: false,
    languages: ["English"],
    essentials: ["Day services", "Overnight beds", "Counseling"],
    eligibility: "Youth 18–24.",
    accessibility: "Stairs at main entrance; call ahead for support.",
    hours: "Daily 10:00 AM – 10:00 PM",
    orgName: "Youth Bridge",
  },
  {
    id: "res-7",
    name: "Warm Coat Closet",
    slug: "warm-coat-closet",
    description: "Free jackets, shoes, and weather gear. Sizes for adults and kids.",
    category: "clothing",
    address: "560 Mission St",
    city: "San Francisco",
    state: "CA",
    postalCode: "94105",
    latitude: 37.7886,
    longitude: -122.3974,
    phone: "(415) 555-0177",
    verificationStatus: "community",
    lastVerifiedAt: "2026-07-03",
    openStatus: "open_now",
    nextOpenLabel: "Open until 4:00 PM",
    walkInAllowed: true,
    appointmentRequired: false,
    idRequired: false,
    familyFriendly: true,
    petFriendly: false,
    wheelchairAccessible: true,
    languages: ["English", "Tagalog"],
    essentials: ["Jackets", "Shoes", "Socks"],
    eligibility: "Open to all.",
    accessibility: "Wide aisles and seating.",
    hours: "Tue–Sat 10:00 AM – 4:00 PM",
    orgName: "Warm Coat Closet",
  },
  {
    id: "res-8",
    name: "Clean Start Hygiene Hub",
    slug: "clean-start-hygiene-hub",
    description: "Showers, restrooms, hygiene kits, and laundry tokens.",
    category: "hygiene",
    address: "39 Jones St",
    city: "San Francisco",
    state: "CA",
    postalCode: "94102",
    latitude: 37.7818,
    longitude: -122.4122,
    phone: "(415) 555-0121",
    verificationStatus: "verified_org",
    lastVerifiedAt: "2026-07-09",
    openStatus: "open_now",
    nextOpenLabel: "Open until 6:00 PM",
    walkInAllowed: true,
    appointmentRequired: false,
    idRequired: false,
    familyFriendly: true,
    petFriendly: false,
    wheelchairAccessible: true,
    languages: ["English", "Spanish"],
    essentials: ["Showers", "Hygiene kits", "Restrooms"],
    eligibility: "Walk-in. Limited shower slots daily.",
    accessibility: "Accessible shower stalls.",
    hours: "Mon–Fri 8:00 AM – 6:00 PM",
    orgName: "Clean Start Hygiene Hub",
  },
  {
    id: "res-9",
    name: "Care Corner Clinic",
    slug: "care-corner-clinic",
    description: "Walk-in medical triage and mental-health referrals. Not an ER.",
    category: "medical",
    address: "1500 Market St",
    city: "San Francisco",
    state: "CA",
    postalCode: "94102",
    latitude: 37.7754,
    longitude: -122.4182,
    phone: "(415) 555-0102",
    verificationStatus: "verified_org",
    lastVerifiedAt: "2026-07-08",
    openStatus: "open_now",
    nextOpenLabel: "Open until 5:00 PM",
    walkInAllowed: true,
    appointmentRequired: false,
    idRequired: false,
    familyFriendly: true,
    petFriendly: false,
    wheelchairAccessible: true,
    languages: ["English", "Spanish", "Chinese"],
    essentials: ["Medical triage", "Mental-health referral", "First aid"],
    eligibility: "Urgent but non-emergency care.",
    accessibility: "Fully accessible clinic floor.",
    hours: "Mon–Fri 9:00 AM – 5:00 PM",
    orgName: "Care Corner Clinic",
  },
  {
    id: "res-10",
    name: "WorkReady Drop-In",
    slug: "workready-drop-in",
    description: "Resume help, job leads, phone access, and interview clothing.",
    category: "employment",
    address: "201 Turk St",
    city: "San Francisco",
    state: "CA",
    postalCode: "94102",
    latitude: 37.7831,
    longitude: -122.4148,
    phone: "(415) 555-0155",
    verificationStatus: "verified_moderator",
    lastVerifiedAt: "2026-07-04",
    openStatus: "open_now",
    nextOpenLabel: "Open until 3:00 PM",
    walkInAllowed: true,
    appointmentRequired: false,
    idRequired: false,
    familyFriendly: false,
    petFriendly: false,
    wheelchairAccessible: true,
    languages: ["English"],
    essentials: ["Job search", "Internet", "Interview clothes"],
    eligibility: "Adults seeking employment support.",
    accessibility: "Accessible computers.",
    hours: "Mon–Thu 9:00 AM – 3:00 PM",
    orgName: "WorkReady Drop-In",
  },
  {
    id: "res-11",
    name: "Transit Token Desk",
    slug: "transit-token-desk",
    description: "Limited Muni tokens and trip planning support for appointments.",
    category: "transportation",
    address: "1155 Market St",
    city: "San Francisco",
    state: "CA",
    postalCode: "94103",
    latitude: 37.7792,
    longitude: -122.4141,
    phone: "(415) 555-0190",
    verificationStatus: "community",
    lastVerifiedAt: "2026-07-02",
    openStatus: "closing_soon",
    nextOpenLabel: "Closes at 1:00 PM",
    walkInAllowed: true,
    appointmentRequired: false,
    idRequired: false,
    familyFriendly: true,
    petFriendly: false,
    wheelchairAccessible: true,
    languages: ["English", "Spanish"],
    essentials: ["Transit tokens", "Trip planning"],
    eligibility: "For verified appointments when supply remains.",
    accessibility: "Street-level counter.",
    hours: "Mon–Fri 9:00 AM – 1:00 PM",
    orgName: "Transit Token Desk",
  },
  {
    id: "res-12",
    name: "ID & Benefits Help Desk",
    slug: "id-benefits-help-desk",
    description: "Help obtaining ID replacements and navigating benefits paperwork.",
    category: "legal",
    address: "170 Otis St",
    city: "San Francisco",
    state: "CA",
    postalCode: "94103",
    latitude: 37.7714,
    longitude: -122.4191,
    phone: "(415) 555-0148",
    verificationStatus: "verified_org",
    lastVerifiedAt: "2026-07-07",
    openStatus: "appointment",
    nextOpenLabel: "Appointments available",
    walkInAllowed: false,
    appointmentRequired: true,
    idRequired: false,
    familyFriendly: true,
    petFriendly: false,
    wheelchairAccessible: true,
    languages: ["English", "Spanish", "Chinese"],
    essentials: ["ID assistance", "Benefits navigation"],
    eligibility: "Call to schedule. Bring any documents you have.",
    accessibility: "Accessible waiting area.",
    hours: "Tue–Thu 10:00 AM – 4:00 PM",
    orgName: "Civic Support Partners",
  },
  {
    id: "res-13",
    name: "Connect & Charge Lounge",
    slug: "connect-charge-lounge",
    description: "Free Wi‑Fi, device charging, and quiet seating.",
    category: "internet",
    address: "100 Larkin St",
    city: "San Francisco",
    state: "CA",
    postalCode: "94102",
    latitude: 37.7790,
    longitude: -122.4157,
    phone: "(415) 555-0108",
    verificationStatus: "verified_moderator",
    lastVerifiedAt: "2026-07-09",
    openStatus: "open_now",
    nextOpenLabel: "Open until 8:00 PM",
    walkInAllowed: true,
    appointmentRequired: false,
    idRequired: false,
    familyFriendly: true,
    petFriendly: false,
    wheelchairAccessible: true,
    languages: ["English"],
    essentials: ["Wi‑Fi", "Charging", "Restrooms"],
    eligibility: "Open to the public.",
    accessibility: "Elevators and accessible restrooms.",
    hours: "Daily 10:00 AM – 8:00 PM",
    orgName: "City Connect Spaces",
  },
  {
    id: "res-14",
    name: "Sofia’s Temporary Shelter Annex",
    slug: "sofias-temporary-shelter-annex",
    description: "Weather-activated beds during cold nights. Status changes with weather alerts.",
    category: "shelter",
    address: "900 Bryant St",
    city: "San Francisco",
    state: "CA",
    postalCode: "94103",
    latitude: 37.7732,
    longitude: -122.4056,
    phone: "(415) 555-0181",
    verificationStatus: "update_requested",
    lastVerifiedAt: "2026-06-28",
    openStatus: "unconfirmed",
    nextOpenLabel: "Availability unconfirmed",
    walkInAllowed: true,
    appointmentRequired: false,
    idRequired: false,
    familyFriendly: false,
    petFriendly: false,
    wheelchairAccessible: false,
    languages: ["English", "Spanish"],
    essentials: ["Emergency beds"],
    eligibility: "Activated during severe weather.",
    accessibility: "Call ahead for access support.",
    hours: "Weather-dependent",
    orgName: "Sofia’s Outreach",
  },
  {
    id: "res-15",
    name: "Neighborhood Donation Hub",
    slug: "neighborhood-donation-hub",
    description: "Community drop-off for clothing, hygiene kits, and non-perishable food.",
    category: "donation",
    address: "742 Irving St",
    city: "San Francisco",
    state: "CA",
    postalCode: "94122",
    latitude: 37.7641,
    longitude: -122.4650,
    phone: "(415) 555-0129",
    verificationStatus: "community",
    lastVerifiedAt: "2026-07-08",
    openStatus: "open_now",
    nextOpenLabel: "Accepting drop-offs until 5:00 PM",
    walkInAllowed: true,
    appointmentRequired: false,
    idRequired: false,
    familyFriendly: true,
    petFriendly: false,
    wheelchairAccessible: true,
    languages: ["English", "Chinese"],
    essentials: ["Clothing intake", "Hygiene kits", "Canned food"],
    eligibility: "Donors welcome during open hours.",
    accessibility: "Step-free storefront.",
    hours: "Wed–Sun 11:00 AM – 5:00 PM",
    orgName: "Harbor Bridge Collective",
  },
];

export const communityNeeds: CommunityNeed[] = [
  {
    id: "need-1",
    orgName: "Harbor Overnight Shelter",
    title: "40 winter jackets needed by Friday",
    description: "Adult sizes M–XXL preferred. Clean, ready-to-wear.",
    category: "clothing",
    requestedQuantity: 40,
    fulfilledQuantity: 18,
    urgency: "urgent",
    deadline: "2026-07-12",
    verified: true,
    latitude: 37.7728,
    longitude: -122.3975,
  },
  {
    id: "need-2",
    orgName: "Clean Start Hygiene Hub",
    title: "Hygiene kits needed this week",
    description: "Toothbrushes, soap, deodorant, menstrual products.",
    category: "hygiene",
    requestedQuantity: 100,
    fulfilledQuantity: 42,
    urgency: "needed_soon",
    deadline: "2026-07-14",
    verified: true,
    latitude: 37.7818,
    longitude: -122.4122,
  },
  {
    id: "need-3",
    orgName: "Mission Evening Meal",
    title: "Volunteers for Saturday meal service",
    description: "Serving and clean-up shifts, 4:00–8:00 PM.",
    category: "volunteer",
    requestedQuantity: 12,
    fulfilledQuantity: 5,
    urgency: "needed_soon",
    deadline: "2026-07-13",
    verified: true,
    latitude: 37.7685,
    longitude: -122.4221,
  },
  {
    id: "need-4",
    orgName: "Warm Coat Closet",
    title: "Driver needed to transport donated blankets",
    description: "One-time pickup in the Mission, drop-off in Bayview.",
    category: "transportation",
    requestedQuantity: 1,
    fulfilledQuantity: 0,
    urgency: "critical",
    deadline: "2026-07-11",
    verified: false,
    latitude: 37.7886,
    longitude: -122.3974,
  },
  {
    id: "need-5",
    orgName: "Harbor Bridge Collective",
    title: "Temporary storage space for weekend drive",
    description: "Dry indoor space for sorted donations Sat–Mon.",
    category: "storage",
    requestedQuantity: 1,
    fulfilledQuantity: 0,
    urgency: "normal",
    deadline: "2026-07-15",
    verified: true,
    latitude: 37.7641,
    longitude: -122.4650,
  },
];

export const donationLocations: DonationLocation[] = [
  {
    id: "don-1",
    name: "Harbor Bridge Drop-Off",
    hostName: "Harbor Bridge Collective",
    address: "742 Irving St, San Francisco, CA",
    description: "Staffed drop-off for clothing and hygiene items.",
    status: "active",
    acceptedItems: ["Clothing", "Hygiene products", "Blankets"],
    capacityStatus: "open",
    latitude: 37.7641,
    longitude: -122.4650,
    hours: "Wed–Sun 11:00 AM – 5:00 PM",
  },
  {
    id: "don-2",
    name: "Sunset School Supply Bin",
    hostName: "Sunset Community School",
    address: "1550 16th Ave, San Francisco, CA",
    description: "Temporary weekend drive for jackets and backpacks.",
    status: "active",
    acceptedItems: ["Clothing", "Backpacks", "School supplies"],
    capacityStatus: "limited",
    latitude: 37.7595,
    longitude: -122.4742,
    hours: "Sat–Sun 10:00 AM – 2:00 PM",
  },
  {
    id: "don-3",
    name: "Market Street Lobby Bin",
    hostName: "Civic Support Partners",
    address: "1 Market St, San Francisco, CA",
    description: "Indoor lobby collection for sealed food and hygiene kits.",
    status: "under_review",
    acceptedItems: ["Food", "Hygiene products"],
    capacityStatus: "open",
    latitude: 37.7936,
    longitude: -122.3942,
    hours: "Mon–Fri 9:00 AM – 5:00 PM",
  },
];

export const volunteerOpportunities: VolunteerOpportunity[] = [
  {
    id: "vol-1",
    title: "Saturday meal service",
    orgName: "Mission Evening Meal",
    description: "Help plate meals and clean dining areas.",
    location: "298 Valencia St",
    startTime: "2026-07-12T16:00:00",
    volunteersNeeded: 12,
    volunteersRegistered: 5,
  },
  {
    id: "vol-2",
    title: "Hygiene kit packing",
    orgName: "Clean Start Hygiene Hub",
    description: "Assemble kits for weekday distribution.",
    location: "39 Jones St",
    startTime: "2026-07-14T10:00:00",
    volunteersNeeded: 8,
    volunteersRegistered: 3,
  },
  {
    id: "vol-3",
    title: "Clothing sort morning",
    orgName: "Warm Coat Closet",
    description: "Sort jackets by size and season.",
    location: "560 Mission St",
    startTime: "2026-07-15T09:00:00",
    volunteersNeeded: 6,
    volunteersRegistered: 2,
  },
  {
    id: "vol-4",
    title: "Shelter evening welcome",
    orgName: "Harbor Overnight Shelter",
    description: "Greet guests and help with intake logistics.",
    location: "450 Townsend St",
    startTime: "2026-07-11T17:30:00",
    volunteersNeeded: 4,
    volunteersRegistered: 1,
  },
];

export const CATEGORY_LABELS: Record<string, string> = {
  food: "Food",
  shelter: "Shelter",
  clothing: "Clothing",
  hygiene: "Hygiene",
  medical: "Medical",
  employment: "Employment",
  transportation: "Transportation",
  legal: "Legal help",
  internet: "Internet & charging",
  donation: "Donation locations",
};
